### ISSUE TITLE
Add ability to receive "Password Reset" emails

### ISSUE THREAD

**Issue by juliaelman** [18F/afsbirez#104]
*Issue*
We currently do not have a way for users to receive a password reset email for their user account.

*Fix*
- [ ] Add ability to send emails to users
- [ ] Hook in "Password reset" to this functionality

*Notes*
See Django's docs on how to set that up here [https://docs.djangoproject.com/en/1.8/topics/auth/default/#django.contrib.auth.forms.PasswordResetForm](https://docs.djangoproject.com/en/1.8/topics/auth/default/#django.contrib.auth.forms.PasswordResetForm)

**Comment by juliaelman** [comment]
@catherinedevlin I think this one is completed?

**Comment by catherinedevlin** [comment]
@juliaelman ah yes - this is closed by https://github.com/18F/afsbirez/pull/121.  Thanks!
