### ISSUE TITLE
You published your SECRET_KEY in your repository

### ISSUE THREAD

**Issue by adewes** [18F/afsbirez#126]
Hey, it seems that you published your `SECRET_KEY` in your repository. Probably this is just a test value and you know what you're doing, just creating this issue in case you did this inadverently.

Here you can find some more information about the issue:

https://www.quantifiedcode.com/app/project/gh:18F:afsbirez?groups=code_patterns%3A1Wit6MHp%3Af0

**Comment by DavidEBest** [comment]
It is just a test value, but thank you for pointing that out, @adewes!
