### ISSUE TITLE
Add updated copy + styling for logged out homepage

### ISSUE THREAD

**Issue by juliaelman** [18F/afsbirez#131]
Per conversation with @DavidEBest, we are currently still in need of a logged out homepage.

**Comment by DavidEBest** [comment]
The goal is to have a basic search/splash page to provide some context for the unauthenticated user. 
Content should be similar to the wire frame already delivered, but does not need 'Success stories'.

This has not been directly requested by the client, but will improve the functionality of the site in its pre-integration state.
