### ISSUE TITLE
Blank names accepted

### ISSUE THREAD

**Issue by catherinedevlin** [18F/afsbirez#159]
As of commit 58af3, on the Eligibility page, fields like "Has your firm been convicted of a fraud..." / "provide the name" accept empty names without complaining in on-page or final validation.

This looks small enough that it would probably be a good way for me to ramp toward being useful on the front-end code, so I'm going to assign myself.

**Comment by DavidEBest** [comment]
Hmm. That shouldn’t be the case. The workflow includes required = true. Either the ask_if / required relationship got busted or required isn’t checking for an empty string.
