### ISSUE TITLE
Time percentage not validated

### ISSUE THREAD

**Issue by catherinedevlin** [18F/afsbirez#161]
As of commit 58af3, on the Principal Investigator page, the "What percentage of the principal investigator's total time will be on the project?" field doesn't complain about entries like "110%", "-30%", "mind your own business", etc.

This looks small enough that it would probably be a good way for me to ramp toward being useful on the front-end code, so I'm going to assign myself.

**Comment by DavidEBest** [comment]
This should be addressed in #172.

**Comment by catherinedevlin** [comment]
Fixed in master.
