### ISSUE TITLE
email addresses not validated

### ISSUE THREAD

**Issue by catherinedevlin** [18F/afsbirez#162]
As of commit 58af3, on the Principal Investigator page (and probably elsewhere), there's no validation for legitimate email addresses.

However, this MIGHT be a good thing, if we want to accept answers like "None", "Unknown", etc.  Opinions?

This looks small enough that it would probably be a good way for me to ramp toward being useful on the front-end code, so I'm going to assign myself.

**Comment by DavidEBest** [comment]
This should be addressed in #172.

**Comment by catherinedevlin** [comment]
Fixed in master.
