### ISSUE TITLE
invalid % rates fail silently

### ISSUE THREAD

**Issue by catherinedevlin** [18F/afsbirez#165]
As of commit 58af3, on the Totals page, entering a non-numeric value in fields like "General & Administrative Rate" appears to be accepted, but no values are calculated for the dependent fields like "General & Administrative Cost" - even after you go back and replace the % values with legitimate percentages.

**Comment by catherinedevlin** [comment]
Fixed now - though % greater than 100% are considered invalid.  Since percentages are applied against fields like "Fee or Profit Rate (%)", it seems fundamentally conceivable (though horrifying) for rates to go above 100%.  Do we want to leave that possible?

**Comment by DavidEBest** [comment]
Yuck. I'd prefer to cap it at 100 for the time being, but that is a valid point. Right now, it is limited to the range 0-100.

**Comment by catherinedevlin** [comment]
OK, closing for now and we can change later if we want.  Thanks!
