### ISSUE TITLE
Empty popup for "Add to my topics" when not signed in

### ISSUE THREAD

**Issue by catherinedevlin** [18F/afsbirez#168]
As of commit 75902b, if I am not logged on, the "Add to my topics" link is available, but clicking it brings up an empty popup (no text).

**Comment by DavidEBest** [comment]
D'oh. This is related to the switch to the separate pages for signin/signup.

**Comment by DavidEBest** [comment]
This should be addressed by #170 .

**Comment by catherinedevlin** [comment]
Confirmed fixed in master.
